voxpupuli/puppet-rvm

lib/puppet/provider/rvm_gem/gem.rb

The name check for an installed gem should be exact and not globbed. Right now a specification for "redis" would match both the "hiredis" and "redis" gems.

Name check should be exact, not globbed

---

manifests/passenger/apache.pp

If installing passenger via the gem, this would allow someone to not have to install mod_passenger.

allow override to not install mod_passenger if just installing the gem

---

manifests/system.pp

Running gpg2 directly fails on systems without this command.  Puppet pre checks for commands in the path.

Use which to test for gpg2

---

manifests/dependencies/centos.pp
manifests/passenger/dependencies/centos.pp

This was the least impactful way to fix this so that it works for CentOS/RHEL 7 without changing the logic entirely.

Fixes #80 - CentOS 7 libcurl-devel dependency

---

manifests/init.pp
manifests/params.pp
manifests/system.pp

I've been having lots of trouble with a Debian 7 Vagrant box build not adding the key. Using `keyserver.ubuntu.com` rather than `keys.gnupg.net` works fine, I've no idea why. I've been pragmatic and added the option to specify this.
It's a non disruptive change which could be useful for other users. Let me know if you require other changes for this to be merged.

Added option to specify the key_server

---

manifests/system.pp

Currently the key_server parameter is not passed to the rvm::gnupg_key class and thus custom key server locations can not be specified in the manifest.

Allow custom key_server paramter for gnupg keys

---

manifests/system.pp
manifests/system_user.pp
spec/classes/system_spec.rb
spec/defines/system_user_spec.rb

- use `pw groupmod` to modify the rvm group
- curl is in /usr/local/bin
- added rspec tests

added support for freebsd and tests for freebsd/darwin

---

manifests/group.pp
manifests/system_user.pp

It is common practice to use different UID/GID ranges for human users and groups vs users and groups used for services. Adding the users and groups as system users and groups ensures this.
Many distros do this as well when a user or group is created by a package. For example, see https://www.debian.org/doc/debian-policy/ch-opersys.html#s9.2

System user and group

---

README.markdown

I'm trying to get RVM with passenger working; and I started with the heira syntax.  What I've found is that the passenger support requires (1) you to be consistent with either using or omitting the ruby- prefix in order to get started, and (2) ultimately you need to include the ruby- prefix as that's what's included in the generated Apache configuration.  To save others a bit of time, I suggest updating the docs to include the prefix in the hiera example.

Include ruby- prefix in hiera example.

---

lib/puppet/type/rvm_gem.rb

This tiny patch fix the problem of idempotency (gem is always reinstalled) when using ensure => latest (Issue #114).
The is.is_a? can not be used in a case/when statement if the "case" already applies to 'is'.

Fix idempotency error when using latest.

---

metadata.json

Git clones of http do not follow the https redirect github provides.

Update project url and source to use HTTPS

---

.gitignore
lib/puppet/provider/rvm_system_ruby/rvm_system_ruby.rb
lib/puppet/type/rvm_system_ruby.rb
manifests/init.pp
manifests/system.pp

Allows RVM to mount a Ruby archive this is useful when you have a specific build you wish to mount and especially useful when your target host is not able to make outbound connections.

Allow rvm to mount a Ruby

---

lib/puppet/provider/rvm_system_ruby/rvm_system_ruby.rb
lib/puppet/type/rvm_system_ruby.rb
spec/unit/puppet/type/rvm_system_ruby_spec.rb

This should be a parameter that affects whether the --autolibs argument
is passed to the `rvm install` command and what its value is. Currently `autolib_mode` is a property and affects autolibs globally. This caused an error on PE 2015.3.3/Puppet 4.3.2 since there were no getter/setter methods defined for the property.

Convert rvm_system_ruby autolib_mode to parameter

---

lib/puppet/provider/rvm_system_ruby/rvm_system_ruby.rb

I discovered a bug in the provider where I referenced the parameter incorrectly.

Fix autolib_mode parameter references

---

manifests/params.pp

"gnupg_installed" fact is not present by default, and we got this message in puppet4 server log :
WARN  [puppetserver] Puppet Unknown variable: '::gnupg_installed'. at 
An idea is to use the $facts['fact_name'] :
https://docs.puppet.com/puppet/4.10/lang_facts_and_builtin_vars.html#the-factsfactname-hash

Avoid warn with puppet4

---

lib/puppet/provider/rvm_alias/alias.rb
lib/puppet/provider/rvm_gem/gem.rb
lib/puppet/provider/rvm_gemset/gemset.rb

This simultaneously fixes `Lint/UselessAssignment` as we're now making use of the `detail` variables.

Rubocop: Fix Lint/HandleExceptions

---

lib/puppet/provider/rvm_gem/gem.rb

Closes #141
- Update install options to determine rubygems version, and remove deprecated `--no-ri` and `--no-rdoc` if rubygems >= 3.0.0 in favor of `--no-document`
- Strip `default: ` string from gem output before regexing it.  I've found in various cases that there can be multiple instances of the string, so decided to remove all occurrences vs. updating existing regex (open to other suggestions).  Example:
```
rvm 2.6.5 do gem list ^bundler$
*** LOCAL GEMS ***
bundler (default: 2.1.2, 1.17.3)
```

Update deprecated install options, and strip default string from gem output

---

manifests/dependencies/centos.pp
manifests/passenger/dependencies/centos.pp
metadata.json
spec/classes/dependencies_spec.rb

This PR also contains:
* https://github.com/voxpupuli/puppet-rvm/pull/167
* https://github.com/voxpupuli/puppet-rvm/pull/168
* https://github.com/voxpupuli/puppet-rvm/pull/169

Drop EoL Puppet 5

---

metadata.json

The gnupg module doesn't support AIX and we also cannot test on AIX.

Drop AIX support

---

metadata.json

The gnupg module doesn't support windows. Also we cannot run tests on
windows.. This is cherry-picked from #164

Drop Windows support

---

metadata.json

Solaris is not supported by the gnupg module and we cannot test it.
cherry-picked from #164

Drop Solaris support

---

manifests/system.pp

Previously we checked if $signing_keys is defined / not undef. That's always the case. The datatype enforces that it's an array. We need to check if it's not empty.

Fix broken logic for gpg keys
